# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RdAgent < Formula
  desc "RD Agent - lightweight file sync client"
  homepage "https://github.com/jus1990/rd-agent"
  version "0.1.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://rd-brew.s3.ap-northeast-1.amazonaws.com/rd-agent/0.1.5/rd-agent_0.1.5_darwin_amd64.tar.gz"
      sha256 "e39bee03056646a10ba55873dd9cb4d2a58eeeae267b1b0c4dc2f8ba634297ce"

      define_method(:install) do
        bin.install "rd-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://rd-brew.s3.ap-northeast-1.amazonaws.com/rd-agent/0.1.5/rd-agent_0.1.5_darwin_arm64.tar.gz"
      sha256 "3a0bf79e4aec2389e0cb3a9760fc34da56c87630a391f46aed2854136c936d48"

      define_method(:install) do
        bin.install "rd-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://rd-brew.s3.ap-northeast-1.amazonaws.com/rd-agent/0.1.5/rd-agent_0.1.5_linux_amd64.tar.gz"
      sha256 "2b9c0bf930467f2e95b46c1527070f426f948260a07b864d043184e892ed15e6"
      define_method(:install) do
        bin.install "rd-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://rd-brew.s3.ap-northeast-1.amazonaws.com/rd-agent/0.1.5/rd-agent_0.1.5_linux_arm64.tar.gz"
      sha256 "39199dfa2f36554ed74f45b62f46c731240e6eee334af0efa233b71017f85ccf"
      define_method(:install) do
        bin.install "rd-agent"
      end
    end
  end

  test do
    system "#{bin}/rd-agent", "version"
  end
end
